apiVersion: v1
preferences: {}
kind: Config

clusters:
- cluster:
    server: https://<API server endpoint>
    certificate-authority-data: EKS_CERTIFICATE_PLACEHOLDER
  name: eks-cluster-name

contexts:
- context:
    cluster: eks_eks-cluster-name
    user: eks_eks-cluster-name
  name: eks_eks-cluster-name

current-context: eks_eks-cluster-name

users:
- name: eks_eks-cluster-name
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "eks-cluster-name"