apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: nome-applicazione
  namespace: namespace-applicazione
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nome-applicazione
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60