apiVersion: v1
kind: Service
metadata:
  name: nome-applicazione
  namespace: namespace-applicazione
  annotations:
    alb.ingress.kubernetes.io/success-codes: "200,401,403,301,302"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "70"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "60"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
spec:
  type: NodePort
  selector:
    app: nome-applicazione
  ports:
    - name: nome-applicazione
      protocol: TCP
      port: 80    
